# Shamelessly copied from https://github.com/opscode-cookbooks/tomcat/blob/master/.kitchen.cloud.yml
---
driver:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: <%= ENV['AWS_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_url: http://www.getchef.com/chef/install.sh

platforms:
- name: ubuntu-12.04
  driver:
    name: ec2
    image_id: ami-60a10117   # instance type suitable for t2-micro
    # image_id: ami-7aa1010d   # instance type suitable for t1-micro
    flavor_id: t2.micro
    vpc_id: vpc-6648a303
    subnet_id: subnet-0a935c6f
    security_group_ids: sg-16e62d73
    #security_group_ids: sg-xxxxxxxx <= to set if your default SG is not opened for ssh
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
    tags: 
      created-by: test-kitchen
      Name: test-kitchen-confluence-ubuntu-12.04
  run_list:
    - recipe[apt]
    
suites:
- name: confluence-installer-mysql-no-java
  run_list:
  - recipe[confluence]
