---
driver:
  name: vagrant
  customize:
    memory: 2048
  network:
    forwarded_port:
      guest: 8443
      host: 8443
      auto_correct: true

platforms:
- name: centos-6
  driver:
    box: bento/centos-6.7  # vagrant
    image: centos-6-5-x64 # digitalocean

- name: centos-7
  driver:
    box: bento/centos-7.1
    image: centos-7-0-x64

- name: ubuntu-12.04
  run_list:
    - recipe[apt]
  driver:
    box: bento/ubuntu-12.04
    image: ubuntu-12-04-x64

- name: ubuntu-14.04
  run_list:
    - recipe[apt]
  driver:
    box: bento/ubuntu-14.04
    image: ubuntu-14-04-x64

provisioner:
  name: chef_zero
  attributes:
    java:
      install_flavor: oracle
      jdk_version: 8
      oracle:
        accept_oracle_download_terms: true

suites:
- name: installer-mysql
  run_list:
  - recipe[confluence_test::mysql]

- name: installer-postgresql
  run_list:
  - recipe[confluence_test::postgresql]

- name: standalone-mysql
  run_list:
  - recipe[java]
  - recipe[confluence_test::mysql]
  attributes:
    confluence:
      install_type: standalone

- name: standalone-postgresql
  run_list:
  - recipe[java]
  - recipe[confluence_test::postgresql]
  attributes:
    confluence:
      install_type: standalone
