---
driver:
  name: vagrant
  require_chef_omnibus: latest
  customize:
    memory: 2048
  network:
    forwarded_port:
      guest: 8443
      host: 8443
      auto_correct: true

platforms:
- name: centos-6
  driver:
    box: bento/centos-6.7  # vagrant
    image: centos-6-5-x64 # digitalocean
- name: centos-7
  driver:
    box: bento/centos-7.1
    image: centos-7-0-x64

- name: ubuntu-12.04
  driver:
    box: bento/ubuntu-12.04
    image: ubuntu-12-04-x64
- name: ubuntu-14.04
  driver:
    box: bento/ubuntu-14.04
    image: ubuntu-14-04-x64
- name: ubuntu-15.04
  driver:
    box: bento/ubuntu-15.04
    image: ubuntu-15-04-x64
  attributes:
    postgresql:
      # postgresql cookbook doesn't support 15.04 yet.
      version: '9.4'
      enable_pgdg_apt: false

provisioner:
  name: chef_zero
  attributes:
    java:
      install_flavor: oracle
      java_home: /usr/lib/jvm/java-7-oracle
      jdk_version: 7
      oracle:
        accept_oracle_download_terms: true

suites:
- name: confluence-installer-mysql
  run_list:
  - recipe[confluence]
  attributes:
    mysql:
      server_root_password: iloverandompasswordsbutthiswilldo
      server_repl_password: iloverandompasswordsbutthiswilldo
      server_debian_password: iloverandompasswordsbutthiswilldo
- name: confluence-installer-postgresql
  run_list:
  - recipe[confluence]
  attributes:
    confluence:
      database:
        type: postgresql
    postgresql:
      password:
        postgres: iloverandompasswordsbutthiswilldo
- name: confluence-standalone-postgresql
  run_list:
  - recipe[java]
  - recipe[confluence]
  attributes:
    confluence:
      database:
        type: postgresql
      install_type: standalone
    java:
      java_home: /usr/lib/jvm/java-8-oracle
      jdk_version: 8
    postgresql:
      password:
        postgres: iloverandompasswordsbutthiswilldo
