name 'confluence'
maintainer 'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license 'Apache-2.0'
description 'Installs/Configures Atlassian Confluence using custom resources'
version '2.6.24'
issues_url 'https://github.com/sous-chefs/confluence/issues'
source_url 'https://github.com/sous-chefs/confluence'

chef_version '>= 16.0'

supports 'almalinux'
supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'rocky'
supports 'ubuntu'

depends 'ark'
